name: Deploy Live

on: workflow_dispatch

jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest

    env:
      SSH_KEY: ${{ secrets.SSH_KEY_LIVE }}
      SSH_HOST: ${{ secrets.SSH_HOST_LIVE }}
      SSH_USER: ${{ secrets.SSH_USER_LIVE }}
      SSH_DEST_DIR: ${{ secrets.SSH_DEST_DIR_LIVE }}
      LIVE_COMMON_CONFIG: ${{secrets.LIVE_COMMON_CONFIG}}

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm i

      - name: Build project
        run: npm run build

      - name: Process resources
        run: npm run resources

      - name: Setup common.config.json
        run: echo "$LIVE_COMMON_CONFIG" > common.config.json

      - name: Configure SSH setup
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $SSH_HOST > ~/.ssh/known_hosts

      - name: Clear destination directory
        run: ssh $SSH_USER@$SSH_HOST "shopt -s dotglob; rm -rf $SSH_DEST_DIR/*"

      - name: Deploy to live server
        run: |
          rsync -avz --delete --delete-excluded \
          --exclude='.git*' \
          --exclude='node_modules' \
          --exclude='package-lock.json' \
          --exclude='babel.config.js' \
          --exclude='eslint.config.js' \
          --exclude='prettier.config.js' \
          --exclude='tsconfig.json' \
          --exclude='webpack.config.js' \
          --exclude='scripts' \
          --exclude='content/assets/src' \
          --exclude='content/*/*/assets/src' \
          --exclude='core/error/assets/src' \
          ./ $SSH_USER@$SSH_HOST:$SSH_DEST_DIR
